version: "3.9"

services:
  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - net

  auth:
    container_name: auth
    build: ./services/auth
    networks:
      - net

  identifier:
    container_name: identifier
    build: ./services/identifier
    networks:
      - net

  msg:
    container_name: msg
    build: ./services/msg
    networks:
      - net
    depends_on:
      - dbmsg

  dbmsg:
    container_name: dbmsg
    image: postgres:15.3
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - net
    volumes:
      - dbmsgdata:/var/lib/postgresql/data
    
  users:
    container_name: users
    build: ./services/users
    networks:
      - net
    depends_on:
      - dbusers
  
  dbusers:
    container_name: dbusers
    image: postgres:15.3
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - net
    volumes:
      - dbusersdata:/var/lib/postgresql/data



networks:
  net:
    driver: bridge

volumes:
  dbusersdata: null
  dbmsgdata: null